# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20170705_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, default='books/empty.png', upload_to='books/'),
        ),
    ]
